/**
 * FilterBar / chips / List 欄位標題翻譯來源（i18next key）。
 *
 * 用法：
 * - `GenericFilterBar` 會根據 `FilterOption.source` 找到這個 key，並用 `t(labelKey)` 轉成對應語系文字
 * - `formatFilters` 會根據 filterValues 的 key 找到翻譯 key，讓 chips 也能跟著切換
 * - `ResponsiveListDatagrid` 會根據子元件的 `source`（或 label 字串）反查翻譯 key
 */
export const filterLabelMap: Record<string, string> = {
  // ===== 供應商（SupplierList） =====
  name: "filters.supplierName",
  supplierName: "filters.supplierName",
  contact: "filters.contactPerson",
  contactPerson: "filters.contactPerson",
  phone: "filters.phone",

  // ===== 共用（依語意對齊）=====
  billingCycle: "filters.billingCycle",
  active: "filters.activeStatus",
  enabled: "filters.activeStatus",
  note: "filters.note",

  // ===== 報表 / 其他列表常用 =====
  purchaseDate: "filters.purchaseDate",
  saleDate: "filters.saleDate",
  receivedDate: "filters.receivedDate",
  orderDate: "filters.orderDate",
  deliveryDate: "filters.deliveryDate",
  amount: "filters.amount",
  category: "filters.category",
  categoryName: "filters.category",
  customerName: "filters.customerName",
  employeeName: "filters.employeeName",

  // ===== 進貨 / 付款 / 訂單常用 =====
  purchaseNo: "filters.purchaseNo",
  item: "filters.itemName",
  itemName: "filters.itemName",
  totalAmount: "filters.totalAmount",
  paidAmount: "filters.paidAmount",
  balance: "filters.balance",
  details: "filters.details",
  payDate: "filters.paymentDate",
  paymentDate: "filters.paymentDate",
  method: "filters.paymentMethod",
  accountingPeriod: "filters.accountingPeriod",
  status: "filters.orderStatus",
  unpaid: "filters.unpaid",
  partialPaid: "filters.partialPaid",
  accountsPayableTotal: "filters.accountsPayableTotal",
  address: "filters.address",
  orderNo: "filters.orderNo",
  paymentStatus: "filters.paymentStatus",
  orderStatus: "filters.orderStatus",
  orderTotalAmount: "filters.orderTotalAmount",

  // ===== 費用 / 員工 / 稽核 =====
  categoryCode: "filters.categoryCode",
  description: "filters.description",
  unitPrice: "filters.unitPrice",
  accountCode: "filters.accountCode",
  expenseDate: "filters.expenseDate",
  position: "filters.position",
  salary: "filters.salary",
  hireDate: "filters.hireDate",
  employmentStatus: "filters.employmentStatus",
  fullName: "filters.name",
  username: "filters.username",
  role: "filters.role",
  operatorUsername: "filters.username",
  resourceType: "filters.resourceType",
  requestStatus: "filters.requestStatus",
  responseStatus: "filters.responseStatus",
  duration: "filters.duration",
  detail: "filters.detail",
  subject: "filters.subject",
  time: "filters.time",

  // ===== 依 label 反推（FunctionField 可能沒有 source）=====
  "供應商名稱": "filters.supplierName",
  "聯絡人": "filters.contactPerson",
  "電話": "filters.phone",
  "結帳週期": "filters.billingCycle",
  "備註": "filters.note",
  "狀態": "filters.activeStatus",
  "操作": "filters.actions",

  // ===== 費用分類（ExpenseCategoryList）=====
  "費用分類名稱": "filters.expenseCategoryName",
  "切換狀態": "filters.expenseCategoryToggleStatus",

  // ===== 依 label 反推（補足你貼的欄位）=====
  "進貨單號": "filters.purchaseNo",
  "品項名稱": "filters.itemName",
  "總金額": "filters.totalAmount",
  "已付款": "filters.paidAmount",
  "餘額": "filters.balance",
  "明細": "filters.details",
  "付款日期": "filters.paymentDate",
  "付款方式": "filters.paymentMethod",
  "會計期間 (YYYY-MM)": "filters.accountingPeriod",
  "未付款": "filters.unpaid",
  "部分付款": "filters.partialPaid",
  "應付總額": "filters.accountsPayableTotal",
  "地址": "filters.address",
  "訂單編號": "filters.orderNo",
  "收款狀態": "filters.paymentStatus",
  "訂單狀態": "filters.orderStatus",
  "訂單金額": "filters.orderTotalAmount",
  "分類代碼": "filters.categoryCode",
  "描述": "filters.description",
  "單價": "filters.unitPrice",
  "會計科目代碼": "filters.accountCode",
  "支出日期": "filters.expenseDate",
  "員工姓名": "filters.employeeName",
  "職位": "filters.position",
  "薪資": "filters.salary",
  "聘用日期": "filters.hireDate",
  "上現狀態": "filters.employmentStatus",
  "費用頻率": "filters.feeFrequency",
  "費用頻率類型": "filters.feeFrequency",
  "上線狀態": "filters.onlineStatus",
  "發生時間": "filters.occurredAt",
  "發生時間（起訖）": "filters.occurredAtRange",
  "帳號": "filters.username",
  "姓名": "filters.name",
  "角色": "filters.role",
  "資源類型": "filters.resourceType",
  "請求狀態": "filters.requestStatus",
  "回應狀態": "filters.responseStatus",
  "耗時": "filters.duration",
  "詳情": "filters.detail",
  "類別": "filters.category",
  "主旨": "filters.subject",
  "時間": "filters.time",
};
